/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as RegistroValidarEmailRouteImport } from './routes/registro.validar-email'
import { Route as RegistroValidacionExitosaRouteImport } from './routes/registro.validacion-exitosa'
import { Route as RegistroExitoRouteImport } from './routes/registro.exito'
import { Route as RegistroEmpresaRouteImport } from './routes/registro.empresa'
import { Route as OnboardingKycRouteImport } from './routes/onboarding.kyc'
import { Route as OnboardingEnProcesoRouteImport } from './routes/onboarding.en-proceso'
import { Route as OnboardingDatosPersonalesRouteImport } from './routes/onboarding.datos-personales'
import { Route as OnboardingDatosEmpresaRouteImport } from './routes/onboarding.datos-empresa'
import { Route as LegalesTerminosRouteImport } from './routes/legales.terminos'
import { Route as LegalesPrivacidadRouteImport } from './routes/legales.privacidad'
import { Route as LegalesComisionesRouteImport } from './routes/legales.comisiones'
import { Route as LegalesArrepentimientoRouteImport } from './routes/legales.arrepentimiento'
import { Route as AppTransferenciasRouteImport } from './routes/app.transferencias'
import { Route as AppSubcuentasRouteImport } from './routes/app.subcuentas'
import { Route as AppServiciosRouteImport } from './routes/app.servicios'
import { Route as AppSeguridadRouteImport } from './routes/app.seguridad'
import { Route as AppQrRouteImport } from './routes/app.qr'
import { Route as AppLinkPagoRouteImport } from './routes/app.link-pago'
import { Route as AppHistorialRouteImport } from './routes/app.historial'
import { Route as AppDestinatariosRouteImport } from './routes/app.destinatarios'
import { Route as AppCuentaRouteImport } from './routes/app.cuenta'
import { Route as AppCobrosRouteImport } from './routes/app.cobros'
import { Route as AppApiRouteImport } from './routes/app.api'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const RegistroValidarEmailRoute = RegistroValidarEmailRouteImport.update({
  id: '/validar-email',
  path: '/validar-email',
  getParentRoute: () => RegistroRoute,
} as any)
const RegistroValidacionExitosaRoute =
  RegistroValidacionExitosaRouteImport.update({
    id: '/validacion-exitosa',
    path: '/validacion-exitosa',
    getParentRoute: () => RegistroRoute,
  } as any)
const RegistroExitoRoute = RegistroExitoRouteImport.update({
  id: '/exito',
  path: '/exito',
  getParentRoute: () => RegistroRoute,
} as any)
const RegistroEmpresaRoute = RegistroEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => RegistroRoute,
} as any)
const OnboardingKycRoute = OnboardingKycRouteImport.update({
  id: '/onboarding/kyc',
  path: '/onboarding/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingEnProcesoRoute = OnboardingEnProcesoRouteImport.update({
  id: '/onboarding/en-proceso',
  path: '/onboarding/en-proceso',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDatosPersonalesRoute =
  OnboardingDatosPersonalesRouteImport.update({
    id: '/onboarding/datos-personales',
    path: '/onboarding/datos-personales',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingDatosEmpresaRoute = OnboardingDatosEmpresaRouteImport.update({
  id: '/onboarding/datos-empresa',
  path: '/onboarding/datos-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalesTerminosRoute = LegalesTerminosRouteImport.update({
  id: '/legales/terminos',
  path: '/legales/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalesPrivacidadRoute = LegalesPrivacidadRouteImport.update({
  id: '/legales/privacidad',
  path: '/legales/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalesComisionesRoute = LegalesComisionesRouteImport.update({
  id: '/legales/comisiones',
  path: '/legales/comisiones',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalesArrepentimientoRoute = LegalesArrepentimientoRouteImport.update({
  id: '/legales/arrepentimiento',
  path: '/legales/arrepentimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransferenciasRoute = AppTransferenciasRouteImport.update({
  id: '/transferencias',
  path: '/transferencias',
  getParentRoute: () => AppRoute,
} as any)
const AppSubcuentasRoute = AppSubcuentasRouteImport.update({
  id: '/subcuentas',
  path: '/subcuentas',
  getParentRoute: () => AppRoute,
} as any)
const AppServiciosRoute = AppServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => AppRoute,
} as any)
const AppSeguridadRoute = AppSeguridadRouteImport.update({
  id: '/seguridad',
  path: '/seguridad',
  getParentRoute: () => AppRoute,
} as any)
const AppQrRoute = AppQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AppRoute,
} as any)
const AppLinkPagoRoute = AppLinkPagoRouteImport.update({
  id: '/link-pago',
  path: '/link-pago',
  getParentRoute: () => AppRoute,
} as any)
const AppHistorialRoute = AppHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AppRoute,
} as any)
const AppDestinatariosRoute = AppDestinatariosRouteImport.update({
  id: '/destinatarios',
  path: '/destinatarios',
  getParentRoute: () => AppRoute,
} as any)
const AppCuentaRoute = AppCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AppRoute,
} as any)
const AppCobrosRoute = AppCobrosRouteImport.update({
  id: '/cobros',
  path: '/cobros',
  getParentRoute: () => AppRoute,
} as any)
const AppApiRoute = AppApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRouteWithChildren
  '/app/api': typeof AppApiRoute
  '/app/cobros': typeof AppCobrosRoute
  '/app/cuenta': typeof AppCuentaRoute
  '/app/destinatarios': typeof AppDestinatariosRoute
  '/app/historial': typeof AppHistorialRoute
  '/app/link-pago': typeof AppLinkPagoRoute
  '/app/qr': typeof AppQrRoute
  '/app/seguridad': typeof AppSeguridadRoute
  '/app/servicios': typeof AppServiciosRoute
  '/app/subcuentas': typeof AppSubcuentasRoute
  '/app/transferencias': typeof AppTransferenciasRoute
  '/legales/arrepentimiento': typeof LegalesArrepentimientoRoute
  '/legales/comisiones': typeof LegalesComisionesRoute
  '/legales/privacidad': typeof LegalesPrivacidadRoute
  '/legales/terminos': typeof LegalesTerminosRoute
  '/onboarding/datos-empresa': typeof OnboardingDatosEmpresaRoute
  '/onboarding/datos-personales': typeof OnboardingDatosPersonalesRoute
  '/onboarding/en-proceso': typeof OnboardingEnProcesoRoute
  '/onboarding/kyc': typeof OnboardingKycRoute
  '/registro/empresa': typeof RegistroEmpresaRoute
  '/registro/exito': typeof RegistroExitoRoute
  '/registro/validacion-exitosa': typeof RegistroValidacionExitosaRoute
  '/registro/validar-email': typeof RegistroValidarEmailRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRouteWithChildren
  '/app/api': typeof AppApiRoute
  '/app/cobros': typeof AppCobrosRoute
  '/app/cuenta': typeof AppCuentaRoute
  '/app/destinatarios': typeof AppDestinatariosRoute
  '/app/historial': typeof AppHistorialRoute
  '/app/link-pago': typeof AppLinkPagoRoute
  '/app/qr': typeof AppQrRoute
  '/app/seguridad': typeof AppSeguridadRoute
  '/app/servicios': typeof AppServiciosRoute
  '/app/subcuentas': typeof AppSubcuentasRoute
  '/app/transferencias': typeof AppTransferenciasRoute
  '/legales/arrepentimiento': typeof LegalesArrepentimientoRoute
  '/legales/comisiones': typeof LegalesComisionesRoute
  '/legales/privacidad': typeof LegalesPrivacidadRoute
  '/legales/terminos': typeof LegalesTerminosRoute
  '/onboarding/datos-empresa': typeof OnboardingDatosEmpresaRoute
  '/onboarding/datos-personales': typeof OnboardingDatosPersonalesRoute
  '/onboarding/en-proceso': typeof OnboardingEnProcesoRoute
  '/onboarding/kyc': typeof OnboardingKycRoute
  '/registro/empresa': typeof RegistroEmpresaRoute
  '/registro/exito': typeof RegistroExitoRoute
  '/registro/validacion-exitosa': typeof RegistroValidacionExitosaRoute
  '/registro/validar-email': typeof RegistroValidarEmailRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRouteWithChildren
  '/app/api': typeof AppApiRoute
  '/app/cobros': typeof AppCobrosRoute
  '/app/cuenta': typeof AppCuentaRoute
  '/app/destinatarios': typeof AppDestinatariosRoute
  '/app/historial': typeof AppHistorialRoute
  '/app/link-pago': typeof AppLinkPagoRoute
  '/app/qr': typeof AppQrRoute
  '/app/seguridad': typeof AppSeguridadRoute
  '/app/servicios': typeof AppServiciosRoute
  '/app/subcuentas': typeof AppSubcuentasRoute
  '/app/transferencias': typeof AppTransferenciasRoute
  '/legales/arrepentimiento': typeof LegalesArrepentimientoRoute
  '/legales/comisiones': typeof LegalesComisionesRoute
  '/legales/privacidad': typeof LegalesPrivacidadRoute
  '/legales/terminos': typeof LegalesTerminosRoute
  '/onboarding/datos-empresa': typeof OnboardingDatosEmpresaRoute
  '/onboarding/datos-personales': typeof OnboardingDatosPersonalesRoute
  '/onboarding/en-proceso': typeof OnboardingEnProcesoRoute
  '/onboarding/kyc': typeof OnboardingKycRoute
  '/registro/empresa': typeof RegistroEmpresaRoute
  '/registro/exito': typeof RegistroExitoRoute
  '/registro/validacion-exitosa': typeof RegistroValidacionExitosaRoute
  '/registro/validar-email': typeof RegistroValidarEmailRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/registro'
    | '/app/api'
    | '/app/cobros'
    | '/app/cuenta'
    | '/app/destinatarios'
    | '/app/historial'
    | '/app/link-pago'
    | '/app/qr'
    | '/app/seguridad'
    | '/app/servicios'
    | '/app/subcuentas'
    | '/app/transferencias'
    | '/legales/arrepentimiento'
    | '/legales/comisiones'
    | '/legales/privacidad'
    | '/legales/terminos'
    | '/onboarding/datos-empresa'
    | '/onboarding/datos-personales'
    | '/onboarding/en-proceso'
    | '/onboarding/kyc'
    | '/registro/empresa'
    | '/registro/exito'
    | '/registro/validacion-exitosa'
    | '/registro/validar-email'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/registro'
    | '/app/api'
    | '/app/cobros'
    | '/app/cuenta'
    | '/app/destinatarios'
    | '/app/historial'
    | '/app/link-pago'
    | '/app/qr'
    | '/app/seguridad'
    | '/app/servicios'
    | '/app/subcuentas'
    | '/app/transferencias'
    | '/legales/arrepentimiento'
    | '/legales/comisiones'
    | '/legales/privacidad'
    | '/legales/terminos'
    | '/onboarding/datos-empresa'
    | '/onboarding/datos-personales'
    | '/onboarding/en-proceso'
    | '/onboarding/kyc'
    | '/registro/empresa'
    | '/registro/exito'
    | '/registro/validacion-exitosa'
    | '/registro/validar-email'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/registro'
    | '/app/api'
    | '/app/cobros'
    | '/app/cuenta'
    | '/app/destinatarios'
    | '/app/historial'
    | '/app/link-pago'
    | '/app/qr'
    | '/app/seguridad'
    | '/app/servicios'
    | '/app/subcuentas'
    | '/app/transferencias'
    | '/legales/arrepentimiento'
    | '/legales/comisiones'
    | '/legales/privacidad'
    | '/legales/terminos'
    | '/onboarding/datos-empresa'
    | '/onboarding/datos-personales'
    | '/onboarding/en-proceso'
    | '/onboarding/kyc'
    | '/registro/empresa'
    | '/registro/exito'
    | '/registro/validacion-exitosa'
    | '/registro/validar-email'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRouteWithChildren
  LegalesArrepentimientoRoute: typeof LegalesArrepentimientoRoute
  LegalesComisionesRoute: typeof LegalesComisionesRoute
  LegalesPrivacidadRoute: typeof LegalesPrivacidadRoute
  LegalesTerminosRoute: typeof LegalesTerminosRoute
  OnboardingDatosEmpresaRoute: typeof OnboardingDatosEmpresaRoute
  OnboardingDatosPersonalesRoute: typeof OnboardingDatosPersonalesRoute
  OnboardingEnProcesoRoute: typeof OnboardingEnProcesoRoute
  OnboardingKycRoute: typeof OnboardingKycRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/registro/validar-email': {
      id: '/registro/validar-email'
      path: '/validar-email'
      fullPath: '/registro/validar-email'
      preLoaderRoute: typeof RegistroValidarEmailRouteImport
      parentRoute: typeof RegistroRoute
    }
    '/registro/validacion-exitosa': {
      id: '/registro/validacion-exitosa'
      path: '/validacion-exitosa'
      fullPath: '/registro/validacion-exitosa'
      preLoaderRoute: typeof RegistroValidacionExitosaRouteImport
      parentRoute: typeof RegistroRoute
    }
    '/registro/exito': {
      id: '/registro/exito'
      path: '/exito'
      fullPath: '/registro/exito'
      preLoaderRoute: typeof RegistroExitoRouteImport
      parentRoute: typeof RegistroRoute
    }
    '/registro/empresa': {
      id: '/registro/empresa'
      path: '/empresa'
      fullPath: '/registro/empresa'
      preLoaderRoute: typeof RegistroEmpresaRouteImport
      parentRoute: typeof RegistroRoute
    }
    '/onboarding/kyc': {
      id: '/onboarding/kyc'
      path: '/onboarding/kyc'
      fullPath: '/onboarding/kyc'
      preLoaderRoute: typeof OnboardingKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/en-proceso': {
      id: '/onboarding/en-proceso'
      path: '/onboarding/en-proceso'
      fullPath: '/onboarding/en-proceso'
      preLoaderRoute: typeof OnboardingEnProcesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/datos-personales': {
      id: '/onboarding/datos-personales'
      path: '/onboarding/datos-personales'
      fullPath: '/onboarding/datos-personales'
      preLoaderRoute: typeof OnboardingDatosPersonalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/datos-empresa': {
      id: '/onboarding/datos-empresa'
      path: '/onboarding/datos-empresa'
      fullPath: '/onboarding/datos-empresa'
      preLoaderRoute: typeof OnboardingDatosEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legales/terminos': {
      id: '/legales/terminos'
      path: '/legales/terminos'
      fullPath: '/legales/terminos'
      preLoaderRoute: typeof LegalesTerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legales/privacidad': {
      id: '/legales/privacidad'
      path: '/legales/privacidad'
      fullPath: '/legales/privacidad'
      preLoaderRoute: typeof LegalesPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legales/comisiones': {
      id: '/legales/comisiones'
      path: '/legales/comisiones'
      fullPath: '/legales/comisiones'
      preLoaderRoute: typeof LegalesComisionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legales/arrepentimiento': {
      id: '/legales/arrepentimiento'
      path: '/legales/arrepentimiento'
      fullPath: '/legales/arrepentimiento'
      preLoaderRoute: typeof LegalesArrepentimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transferencias': {
      id: '/app/transferencias'
      path: '/transferencias'
      fullPath: '/app/transferencias'
      preLoaderRoute: typeof AppTransferenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subcuentas': {
      id: '/app/subcuentas'
      path: '/subcuentas'
      fullPath: '/app/subcuentas'
      preLoaderRoute: typeof AppSubcuentasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/servicios': {
      id: '/app/servicios'
      path: '/servicios'
      fullPath: '/app/servicios'
      preLoaderRoute: typeof AppServiciosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seguridad': {
      id: '/app/seguridad'
      path: '/seguridad'
      fullPath: '/app/seguridad'
      preLoaderRoute: typeof AppSeguridadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/qr': {
      id: '/app/qr'
      path: '/qr'
      fullPath: '/app/qr'
      preLoaderRoute: typeof AppQrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/link-pago': {
      id: '/app/link-pago'
      path: '/link-pago'
      fullPath: '/app/link-pago'
      preLoaderRoute: typeof AppLinkPagoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historial': {
      id: '/app/historial'
      path: '/historial'
      fullPath: '/app/historial'
      preLoaderRoute: typeof AppHistorialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/destinatarios': {
      id: '/app/destinatarios'
      path: '/destinatarios'
      fullPath: '/app/destinatarios'
      preLoaderRoute: typeof AppDestinatariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cuenta': {
      id: '/app/cuenta'
      path: '/cuenta'
      fullPath: '/app/cuenta'
      preLoaderRoute: typeof AppCuentaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cobros': {
      id: '/app/cobros'
      path: '/cobros'
      fullPath: '/app/cobros'
      preLoaderRoute: typeof AppCobrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/api': {
      id: '/app/api'
      path: '/api'
      fullPath: '/app/api'
      preLoaderRoute: typeof AppApiRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApiRoute: typeof AppApiRoute
  AppCobrosRoute: typeof AppCobrosRoute
  AppCuentaRoute: typeof AppCuentaRoute
  AppDestinatariosRoute: typeof AppDestinatariosRoute
  AppHistorialRoute: typeof AppHistorialRoute
  AppLinkPagoRoute: typeof AppLinkPagoRoute
  AppQrRoute: typeof AppQrRoute
  AppSeguridadRoute: typeof AppSeguridadRoute
  AppServiciosRoute: typeof AppServiciosRoute
  AppSubcuentasRoute: typeof AppSubcuentasRoute
  AppTransferenciasRoute: typeof AppTransferenciasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiRoute: AppApiRoute,
  AppCobrosRoute: AppCobrosRoute,
  AppCuentaRoute: AppCuentaRoute,
  AppDestinatariosRoute: AppDestinatariosRoute,
  AppHistorialRoute: AppHistorialRoute,
  AppLinkPagoRoute: AppLinkPagoRoute,
  AppQrRoute: AppQrRoute,
  AppSeguridadRoute: AppSeguridadRoute,
  AppServiciosRoute: AppServiciosRoute,
  AppSubcuentasRoute: AppSubcuentasRoute,
  AppTransferenciasRoute: AppTransferenciasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface RegistroRouteChildren {
  RegistroEmpresaRoute: typeof RegistroEmpresaRoute
  RegistroExitoRoute: typeof RegistroExitoRoute
  RegistroValidacionExitosaRoute: typeof RegistroValidacionExitosaRoute
  RegistroValidarEmailRoute: typeof RegistroValidarEmailRoute
}

const RegistroRouteChildren: RegistroRouteChildren = {
  RegistroEmpresaRoute: RegistroEmpresaRoute,
  RegistroExitoRoute: RegistroExitoRoute,
  RegistroValidacionExitosaRoute: RegistroValidacionExitosaRoute,
  RegistroValidarEmailRoute: RegistroValidarEmailRoute,
}

const RegistroRouteWithChildren = RegistroRoute._addFileChildren(
  RegistroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRouteWithChildren,
  LegalesArrepentimientoRoute: LegalesArrepentimientoRoute,
  LegalesComisionesRoute: LegalesComisionesRoute,
  LegalesPrivacidadRoute: LegalesPrivacidadRoute,
  LegalesTerminosRoute: LegalesTerminosRoute,
  OnboardingDatosEmpresaRoute: OnboardingDatosEmpresaRoute,
  OnboardingDatosPersonalesRoute: OnboardingDatosPersonalesRoute,
  OnboardingEnProcesoRoute: OnboardingEnProcesoRoute,
  OnboardingKycRoute: OnboardingKycRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
